pom.xml, src/test/resources/testCase.xiidm
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
**What is the current behavior?** *(You can also link to an open issue here)*
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
(if any of the questions/checkboxes don't apply, please delete them entirely)
=> Migrate to PowSyBl WS 2.1.0

src/main/java/com/powsybl/caseserver/elasticsearch/CaseInfosRepository.java, src/main/java/com/powsybl/caseserver/elasticsearch/CaseInfosService.java, src/main/java/com/powsybl/caseserver/repository/JPAConfig.java, src/test/java/com/powsybl/caseserver/CaseControllerTest.java, src/test/java/com/powsybl/caseserver/CaseFileNameParserTests.java, src/test/java/com/powsybl/caseserver/CaseInfosELRepositoryTests.java, src/test/java/com/powsybl/caseserver/ContextConfigurationWithTestChannel.java, src/test/java/com/powsybl/caseserver/ScheduledCaseCleanerTest.java, src/test/java/com/powsybl/caseserver/elasticsearch/DisableElasticsearch.java, src/test/java/com/powsybl/caseserver/elasticsearch/EmbeddedElasticsearch.java
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
**What is the current behavior?** *(You can also link to an open issue here)*
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
(if any of the questions/checkboxes don't apply, please delete them entirely)
=> Fix elasticsearch starting with tests

pom.xml, src/main/java/com/powsybl/caseserver/CaseController.java, src/main/java/com/powsybl/caseserver/dto/CaseInfos.java, src/main/java/com/powsybl/caseserver/dto/entsoe/EntsoeCaseInfos.java, src/main/java/com/powsybl/caseserver/elasticsearch/CaseInfosService.java, src/test/java/com/powsybl/caseserver/CaseControllerTest.java, src/test/java/com/powsybl/caseserver/CaseFileNameParserTests.java, src/test/java/com/powsybl/caseserver/CaseInfosELRepositoryTests.java
Update to powsybl-parent-ws 10
=> upgrade to powsybl-parent-ws 10

pom.xml, src/main/java/com/powsybl/caseserver/CaseApplication.java, src/main/java/com/powsybl/caseserver/elasticsearch/CaseInfosService.java, src/main/java/com/powsybl/caseserver/elasticsearch/ESConfig.java, src/main/java/com/powsybl/caseserver/repository/CaseMetadataEntity.java, src/main/java/com/powsybl/caseserver/repository/JPAConfig.java, src/main/resources/config/application.yaml, src/test/java/com/powsybl/caseserver/CaseControllerTest.java, src/test/java/com/powsybl/caseserver/datasource/util/CaseDataSourceControllerTest.java, src/test/java/com/powsybl/caseserver/elasticsearch/EmbeddedElasticsearch.java, src/test/resources/application-default.yaml
=> springboot 3.1.2

pom.xml
=> Parent 17: update liquibase maven plugin

pom.xml, src/test/resources/testCase.xiidm
=> powsybl ws dependencies 2.5.0

pom.xml, src/main/java/com/powsybl/caseserver/CaseApplication.java
=> update to powsybl-ws-dependencies 2.6.0

src/main/java/com/powsybl/caseserver/CaseController.java, src/main/java/com/powsybl/caseserver/CaseException.java, src/main/java/com/powsybl/caseserver/CaseService.java, src/main/java/com/powsybl/caseserver/RestResponseEntityExceptionHandler.java, src/main/java/com/powsybl/caseserver/dto/ExportCaseInfos.java, src/main/java/com/powsybl/caseserver/dto/ExportNetworkInfos.java, src/test/java/com/powsybl/caseserver/CaseControllerTest.java
- [ x] The commit message follows our guidelines
- [ x] Tests for the changes have been added (for bug fixes / features)
- [x ] Docs have been added / updated (for bug fixes / features)
Feature
Format cannot be chosen when getting a case.
Format can be chosen when getting a case, along with format parameters.
- [ x] Yes
- [x ] The *Breaking Change* or *Deprecated* label has been added
- [ x] The …
=> Export case with choosen format

src/main/java/com/powsybl/caseserver/CaseController.java, src/main/java/com/powsybl/caseserver/CaseService.java, src/test/java/com/powsybl/caseserver/CaseControllerTest.java
=> Separate download and convert format (cases)

src/test/java/com/powsybl/caseserver/elasticsearch/EmbeddedElasticsearch.java
See https://github.com/gridsuite/deployment/pull/404
=> Disable index auto-creation by ElasticSearch

src/main/java/com/powsybl/caseserver/CaseController.java, src/test/java/com/powsybl/caseserver/CaseControllerTest.java
=> Refactor duplication endpoint

src/main/java/com/powsybl/caseserver/CaseController.java, src/main/java/com/powsybl/caseserver/CaseService.java
=> rename exported file when convert case

pom.xml, src/test/resources/testCase.xiidm
Update to powsybl/powsybl-ws-dependencies#44
=> upgrade to powsybl-dependencies 2024.2.0

src/main/java/com/powsybl/caseserver/CaseService.java, src/test/java/com/powsybl/caseserver/CaseControllerTest.java
=> fix a bug affecting duplication of non indexed cases

src/main/java/com/powsybl/caseserver/service/FsCaseService.java, src/main/java/com/powsybl/caseserver/service/S3CaseService.java, src/test/java/com/powsybl/caseserver/service/AbstractCaseControllerTest.java
No
Bug fix
A nullPointerException is raised when file is null in getCaseInfos(Path file)
The error is well loggeg.
=> Fix error log for non existing file

src/main/java/com/powsybl/caseserver/CaseController.java, src/test/java/com/powsybl/caseserver/service/AbstractCaseControllerTest.java
=> get case base name from caseName with extension

pom.xml
Depends on powsybl/powsybl-ws-dependencies#63
=> upgrade to powsybl ws dependencies 2.17.0

pom.xml
**Does this PR introduce a new Powsybl Action implying to be implemented in simulators or pypowsybl?**
=> clean pom file

src/main/java/com/powsybl/caseserver/service/S3CaseService.java, src/test/java/com/powsybl/caseserver/ScheduledCaseCleanerTest.java
No
Add comment on S3 performance with archives containing a single file.
=> Add comment on possible optimization for S3 single file archives

src/main/resources/application-local.yml, src/main/resources/config/application.yaml
No
Change cron job running every minutes at 2:00 to once at 2:00
=> Fix cron job running every minutes at 2:00 to once at 2:00

src/test/resources/application-default.yaml
=> Update hibernate binder for logging (Hibernate 6)

pom.xml
=> Upgrade to powsybl dependencies 2025.0.1

pom.xml, src/main/java/com/powsybl/caseserver/CaseController.java, src/main/java/com/powsybl/caseserver/repository/StorageConfig.java, src/main/java/com/powsybl/caseserver/service/CaseObserver.java, src/main/java/com/powsybl/caseserver/service/CaseService.java, src/main/java/com/powsybl/caseserver/service/FsCaseService.java, src/main/java/com/powsybl/caseserver/service/S3CaseService.java
- [x ] The commit message follows our guidelines
No
Feature
No Prometheus metrics
Add some Prometheus metrics
- [ x] No
None
=> Add import and export metrics

src/main/java/com/powsybl/caseserver/CaseController.java, src/main/resources/config/application.yaml, src/test/java/com/powsybl/caseserver/service/AbstractCaseControllerTest.java
Fix sonar warnings from https://github.com/powsybl/powsybl-case-server/commit/3b64e815c0adf27e6f75b5bb144fe6cd9626872b
=> Fix sonar warnings from PR #96

src/main/java/com/powsybl/caseserver/CaseController.java, src/main/java/com/powsybl/caseserver/service/CaseService.java, src/main/java/com/powsybl/caseserver/service/FsCaseService.java, src/main/java/com/powsybl/caseserver/service/S3CaseService.java, src/test/java/com/powsybl/caseserver/service/AbstractCaseControllerTest.java, src/test/java/com/powsybl/caseserver/service/CaseServiceTest.java, src/test/java/com/powsybl/caseserver/service/FsCaseControllerTest.java, src/test/java/com/powsybl/caseserver/service/S3CaseControllerTest.java
Revert https://github.com/powsybl/powsybl-case-server/commit/3b64e815c0adf27e6f75b5bb144fe6cd9626872b and https://github.com/powsybl/powsybl-case-server/commit/8e34566eb3b3feec77f3acddd0a89b2badd38ca4 that shouldn't be in PROD yet.
=> Revert #96 and #104

src/main/java/com/powsybl/caseserver/datasource/S3CaseDataSourceService.java, src/main/java/com/powsybl/caseserver/service/FsCaseService.java, src/main/java/com/powsybl/caseserver/service/S3CaseService.java
=> Sonar warning on direct use of regex

src/main/java/com/powsybl/caseserver/CaseApplication.java, src/main/java/com/powsybl/caseserver/service/S3CaseService.java
Cherry-pick of : https://github.com/powsybl/powsybl-case-server/commit/d45d6c10f18eac8d676b7d3f58b83236ba367507
=> Prepare patch v2.20.0

pom.xml
=> Release v2.24.0
